srun: error: resolve_ctls_from_dns_srv: res_nsearch error: Unknown host
srun: error: fetch_config: DNS SRV lookup failed
srun: error: _establish_config_source: failed to fetch config
srun: fatal: Could not establish a configuration source
wandb: Starting wandb agent üïµÔ∏è
2021-11-03 19:56:39,034 - wandb.wandb_agent - INFO - Running runs: []
2021-11-03 19:56:39,353 - wandb.wandb_agent - INFO - Agent received command: run
2021-11-03 19:56:39,354 - wandb.wandb_agent - INFO - Agent starting run with config:
	ac_update_ratio: 5
	confidence_scale: 0.8675305555139895
	target_entropy: -1.1808159516439658
	use_entropy: False
2021-11-03 19:56:39,360 - wandb.wandb_agent - INFO - About to run command: python3 src/main.py --train --wandb
wandb: Currently logged in as: jjshoots (use `wandb login --relogin` to force relogin)
wandb: WARNING Ignored wandb.init() arg project when running a sweep
wandb: WARNING Ignored wandb.init() arg entity when running a sweep
-----------------------
Using Device cuda:0
-----------------------
wandb: wandb version 0.12.6 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
2021-11-03 19:56:44,370 - wandb.wandb_agent - INFO - Running runs: ['zpnrcfti']
wandb: Tracking run with wandb version 0.12.0
wandb: Syncing run 53681
wandb:  View project at https://wandb.ai/jjshoots/UA3SAC_gym
wandb:  View sweep at https://wandb.ai/jjshoots/UA3SAC_gym/sweeps/nktx8eqi
wandb:  View run at https://wandb.ai/jjshoots/UA3SAC_gym/runs/zpnrcfti
wandb: Run data is saved locally in /home/taij/e2sac/wandb/run-20211103_195642-zpnrcfti
wandb: Run `wandb offline` to turn off syncing.
